config/routes.rb
Rails.application.routes.draw do
  resources :clips
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "main#index"

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :user
  mount_uploader :video, VideoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :video, presence: true

  validates_length_of :title, minimum: 1, maximum: 15
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :clips
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_user_logged_in!
    redirect_to root_path if not user_signed_in?
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: %i[ show edit update destroy ]

  # GET /clips or /clips.json
  def index
    if user_signed_in?
      @clips = current_user.clips.paginate(page: params[:page], per_page: 8)
    else
      redirect_to root_path
    end
  end

  # GET /clips/1 or /clips/1.json
  def show
    @clip = Clip.friendly.find(params[:id])
  end

  # GET /clips/new
  def new
    @clip = current_user.clips.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips or /clips.json
  def create
    @clip = current_user.clips.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: "Clip was successfully created." }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1 or /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: "Clip was successfully updated." }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1 or /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: "Clip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clip_params
      params.require(:clip).permit(:title, :video)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_form.html.erb
<%= form_with(model: clip) do |form| %>
  <% if clip.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <h2><%= pluralize(clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
        <% clip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :video, class: "form-label mt-3" %>
    <%= form.file_field :video, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Upload Clip", class: "btn btn-primary my-3"%>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between">
  <h1>Clips</h1>
  <%= link_to "Upload", new_clip_path, class: "btn btn-primary my-auto" %>
</div>

<% if !@clips.empty? %>
  <div class="d-flex justify-content-center flex-wrap" >
    <% @clips.reverse_each do |clip| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body d-flex flex-column justify-content-around">
          <h3 class="card-title"><%= clip.title %></h3>
          <%= image_tag clip.video.thumb.url, size: "254x254", class: "img-fluid rounded" if clip.video%>
            <%= link_to 'View', clip, class: "btn btn-outline-primary mt-2" %>
            <%= link_to 'Delete', clip, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center mt-2">
    <%= will_paginate @clips, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
<% else %>
  <h3>You don't have any clips</h3>
<% end %>

app/views/clips/new.html.erb
<h1>New Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Back', clips_path %>

app/views/clips/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-column align-items-center">
  <h3><%= @clip.title %></h3>

  <%= video_tag @clip.video, :controls => true %>

  <script>
      let copyToClipboard = () => {
          let text = document.getElementById("textToCopy");
          text.select();
          document.execCommand("copy");
      }
  </script>

  <div class="row my-2">
    <div class="col-auto">
      <input id="textToCopy" class="form-control" value=<%= request.url %> readonly>
    </div>
    <div class="col-auto">
      <button onclick="copyToClipboard()" class="btn btn-outline-secondary">
        Copy
      </button>
    </div>
  </div>
  <div class="mt-2">
    <%= link_to 'Back', clips_path, class: "btn btn-outline-primary" %>
    <% if user_signed_in? and current_user.clips.friendly.exists?(params[:id])%>
      <%= link_to 'Delete', @clip, method: :delete, data: { confirm: 'Are you sure you want to delete this clip?' }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>rails-video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property="og:url"                  content="<%= request.url %>" />
    <meta name="theme-color" content="#0275d8">
    <% if @clip %>
      <meta property="og:type"               content="video" />
      <meta property="og:title"              content="<%= @clip.title %>" />
      <meta property="og:video"              content="<%= @clip.video.url %>" />
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex flex-column">
  <h1 class="mt-3">Welcome to rails-video</h1>
  <br>
  <div>
  <% if !user_signed_in? %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>
  <% else %>
    <%= link_to "Upload", new_clip_path, class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container-fluid">
    <%= link_to "rails-video", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%#= link_to "Tweets", #, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "About", '#', class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-large-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Clips", clips_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Manage Account", edit_user_registration_path, class: "nav-link mr-2" %>
          </li>
          <li class="nav-item mx-1">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item mx-1">
            <%= link_to "Upload", new_clip_path, class: "btn btn-primary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>